# Observe Datasets

In [1]:
import pandas as pd

df = pd.read_csv("../data/Raw/b4sphljrkg5jbwzv.csv")

print(df.shape)
print(df.columns.tolist())
print(df.head(3))

(2960704, 9)
['PERMNO', 'HdrCUSIP', 'Ticker', 'PERMCO', 'MthCalDt', 'MthPrc', 'MthCap', 'MthRet', 'ShrOut']
   PERMNO  HdrCUSIP Ticker  PERMCO    MthCalDt    MthPrc    MthCap    MthRet  \
0   10001  36720410   EWST    7953  1995-01-31  7.750000  17236.00 -0.031250
1   10001  36720410   EWST    7953  1995-02-28  7.546875  16784.25 -0.026210
2   10001  36720410   EWST    7953  1995-03-31  7.500000  16830.00  0.005971

   ShrOut
0    2224
1    2224
2    2244

In [2]:
df2 = pd.read_csv("../data/Raw/b4sphljrkg5jbwzv 2.csv")

print(df2.shape)
print(df2.columns.tolist())
print(df2.head(3))

(2960704, 9)
['PERMNO', 'HdrCUSIP', 'Ticker', 'PERMCO', 'MthCalDt', 'MthPrc', 'MthCap', 'MthRet', 'ShrOut']
   PERMNO  HdrCUSIP Ticker  PERMCO    MthCalDt    MthPrc    MthCap    MthRet  \
0   10001  36720410   EWST    7953  1995-01-31  7.750000  17236.00 -0.031250
1   10001  36720410   EWST    7953  1995-02-28  7.546875  16784.25 -0.026210
2   10001  36720410   EWST    7953  1995-03-31  7.500000  16830.00  0.005971

   ShrOut
0    2224
1    2224
2    2244

In [3]:
ff = pd.read_csv("../data/Raw/F-F_Research_Data_5_Factors_2x3.csv", skiprows=3)

print(ff.head(10))

  Unnamed: 0    Mkt-RF       SMB       HML       RMW       CMA        RF
0     196307     -0.39     -0.48     -0.81      0.64     -1.15      0.27
1     196308      5.08     -0.80      1.70      0.40     -0.38      0.25
2     196309     -1.57     -0.43      0.00     -0.78      0.15      0.27
3     196310      2.54     -1.34     -0.04      2.79     -2.25      0.29
4     196311     -0.86     -0.85      1.73     -0.43      2.27      0.27
5     196312      1.83     -1.89     -0.21      0.12     -0.25      0.29
6     196401      2.27      0.10      1.63      0.21      1.48      0.30
7     196402      1.55      0.33      2.81      0.11      0.81      0.26
8     196403      1.41      1.41      3.29     -2.03      2.98      0.31
9     196404      0.11     -1.48     -0.54     -1.32     -1.13      0.29

In [4]:
ff.tail(10)

,Unnamed: 0,Mkt-RF,SMB,HML,RMW,CMA,RF
806,2017,21.51,-6.27,-13.37,4.56,-11.19,0.80
807,2018,-6.83,-5.06,-9.62,-1.20,0.20,1.81
808,2019,28.40,-6.60,-10.33,3.71,-3.09,2.14
809,2020,23.65,3.74,-46.94,-5.21,-11.70,0.44
810,2021,23.87,-1.02,25.61,26.72,11.67,0.04
811,2022,-21.27,-1.57,25.68,6.55,22.50,1.42
812,2023,21.75,-6.31,-13.98,6.24,-20.61,4.95
813,2024,19.79,-13.52,-8.71,5.03,-9.83,5.26
814,2025,13.30,-9.25,8.41,-10.82,-5.26,4.25
815,Copyright 2026 Eugene F. Fama and Kenneth R. F...,NaN,NaN,NaN,NaN,NaN,NaN

# Clean Minimally

In [5]:
ff = pd.read_csv("../data/Raw/F-F_Research_Data_5_Factors_2x3.csv", skiprows=3)

# rename date column
ff = ff.rename(columns={"Unnamed: 0": "DateKey"})

# keep only numeric rows (monthly data)
ff = ff[pd.to_numeric(ff["DateKey"], errors="coerce").notna()]

# convert to int
ff["DateKey"] = ff["DateKey"].astype(int)

# keep only YYYYMM format (6 digits)
ff = ff[ff["DateKey"] > 100000]

print(ff.tail())
print(ff.shape)

     DateKey    Mkt-RF       SMB       HML       RMW       CMA        RF
746   202509      3.39     -2.18     -1.05     -2.06     -2.22      0.33
747   202510      1.96     -1.30     -3.10     -5.21     -4.03      0.37
748   202511     -0.13      1.47      3.76      1.42      0.68      0.30
749   202512     -0.36     -0.22      2.42      0.40      0.37      0.34
750   202601      1.02      3.26      3.70      1.83      1.81      0.30
(751, 7)

In [6]:
# duplicates
print("Duplicates:", df.duplicated(["PERMNO", "MthCalDt"]).sum())

# missing
print(df[["MthRet", "MthPrc", "MthCap"]].isnull().sum())

# basic sanity
print(df["MthRet"].describe())

Duplicates: 33498
MthRet    37443
MthPrc    36370
MthCap    36370
dtype: int64
count    2.923261e+06
mean     8.577255e-03
std      1.860825e-01
min     -1.000000e+00
25%     -5.375600e-02
50%      3.786000e-03
75%      5.707600e-02
max      3.900000e+01
Name: MthRet, dtype: float64

## Drop missing and duplicates

In [7]:
# sort first
df = df.sort_values(["PERMNO", "MthCalDt"])

# drop exact duplicates (keep first)
df = df.drop_duplicates(subset=["PERMNO", "MthCalDt"], keep="first")

print("Duplicates after:", df.duplicated(["PERMNO", "MthCalDt"]).sum())
print("New shape:", df.shape)

Duplicates after: 0
New shape: (2927206, 9)

In [8]:
df = df.dropna(subset=["MthRet", "MthPrc", "MthCap"])

print("Shape after NA drop:", df.shape)

Shape after NA drop: (2889763, 9)

## Drop Noise (penny stocks and low value stocks)

In [9]:
df["MthPrc_Abs"] = df["MthPrc"].abs()
df = df[df["MthPrc_Abs"] >= 5]

print(df.shape)

(2337142, 10)

## Create DateKey

In [10]:
df["MthCalDt"] = pd.to_datetime(df["MthCalDt"])
df["DateKey"] = df["MthCalDt"].dt.year * 100 + df["MthCalDt"].dt.month

print(df[["MthCalDt", "DateKey"]].head())

    MthCalDt  DateKey
0 1995-01-31   199501
1 1995-02-28   199502
2 1995-03-31   199503
3 1995-04-28   199504
4 1995-05-31   199505

## Validate FF

In [11]:
# duplicates
print("Duplicates:", ff.duplicated(["DateKey"]).sum())

# missing
print(ff.isnull().sum())

# basic stats
print(ff.describe())

Duplicates: 0
DateKey    0
Mkt-RF     0
SMB        0
HML        0
RMW        0
CMA        0
RF         0
dtype: int64
             DateKey
count     751.000000
mean   199435.544607
std      1808.000233
min    196307.000000
25%    197902.500000
50%    199410.000000
75%    201005.500000
max    202601.000000

In [12]:
cols = ["Mkt-RF", "SMB", "HML", "RMW", "CMA", "RF"]

ff[cols] = ff[cols].apply(pd.to_numeric, errors="coerce")
ff[cols] = ff[cols] / 100

print(ff.dtypes)

DateKey      int64
Mkt-RF     float64
SMB        float64
HML        float64
RMW        float64
CMA        float64
RF         float64
dtype: object

In [13]:
df_merged = df.merge(ff, on="DateKey", how="inner")

print("Shape:", df_merged.shape)

Shape: (2337142, 17)

In [14]:
print(df_merged[["DateKey", "MthRet", "Mkt-RF", "SMB"]].head())

print("Unique stocks per month (sample):")
print(df_merged.groupby("DateKey")["PERMNO"].nunique().head())

   DateKey    MthRet  Mkt-RF     SMB
0   199501 -0.031250  0.0180 -0.0307
1   199502 -0.026210  0.0363 -0.0049
2   199503  0.005971  0.0219 -0.0053
3   199504  0.000000  0.0211 -0.0026
4   199505  0.050000  0.0290 -0.0217
Unique stocks per month (sample):
DateKey
199501    6109
199502    6131
199503    6158
199504    6203
199505    6256
Name: PERMNO, dtype: int64

## Target Feature Construction

In [15]:
df_merged["ExcessRet"] = df_merged["MthRet"] - df_merged["RF"]

df_merged[["MthRet", "RF", "ExcessRet"]].head()

     MthRet      RF  ExcessRet
0 -0.031250  0.0042  -0.035450
1 -0.026210  0.0040  -0.030210
2  0.005971  0.0046   0.001371
3  0.000000  0.0044  -0.004400
4  0.050000  0.0054   0.044600

In [16]:
# Winsorize Excess Returns (1% / 99%)
lower = df_merged["ExcessRet"].quantile(0.01)
upper = df_merged["ExcessRet"].quantile(0.99)

df_merged["ExcessRet"] = df_merged["ExcessRet"].clip(lower, upper)

In [17]:
df_merged = df_merged.sort_values(["PERMNO", "MthCalDt"])

df_merged["y_next"] = df_merged.groupby("PERMNO")["ExcessRet"].shift(-1)

df_merged[["PERMNO", "MthCalDt", "ExcessRet", "y_next"]].head(10)

   PERMNO   MthCalDt  ExcessRet    y_next
0   10001 1995-01-31  -0.035450 -0.030210
1   10001 1995-02-28  -0.030210  0.001371
2   10001 1995-03-31   0.001371 -0.004400
3   10001 1995-04-28  -0.004400  0.044600
4   10001 1995-05-31   0.044600  0.055617
5   10001 1995-06-30   0.055617 -0.004500
6   10001 1995-07-31  -0.004500 -0.035003
7   10001 1995-08-31  -0.035003  0.039841
8   10001 1995-09-29   0.039841 -0.035003
9   10001 1995-10-31  -0.035003  0.089550

In [18]:
# Remove last observation

df_merged = df_merged.dropna(subset=["y_next"])

print(df_merged.shape)

(2309143, 19)

In [19]:
df_merged["ret_lag1"] = df_merged.groupby("PERMNO")["ExcessRet"].shift(1)
df_merged[["PERMNO", "MthCalDt", "ExcessRet", "ret_lag1"]].head(10)

   PERMNO   MthCalDt  ExcessRet  ret_lag1
0   10001 1995-01-31  -0.035450       NaN
1   10001 1995-02-28  -0.030210 -0.035450
2   10001 1995-03-31   0.001371 -0.030210
3   10001 1995-04-28  -0.004400  0.001371
4   10001 1995-05-31   0.044600 -0.004400
5   10001 1995-06-30   0.055617  0.044600
6   10001 1995-07-31  -0.004500  0.055617
7   10001 1995-08-31  -0.035003 -0.004500
8   10001 1995-09-29   0.039841 -0.035003
9   10001 1995-10-31  -0.035003  0.039841

In [20]:
# drop NaN created by lag

df_merged = df_merged.dropna(subset=["ret_lag1"])
print(df_merged.shape)

(2281650, 20)

In [21]:
df_merged["ret_lag2"] = df_merged.groupby("PERMNO")["ExcessRet"].shift(2)
df_merged["ret_lag3"] = df_merged.groupby("PERMNO")["ExcessRet"].shift(3)

df_merged = df_merged.dropna(subset=["ret_lag2", "ret_lag3"])

print(df_merged.shape)

(2201855, 22)

In [22]:
df_merged["history_len"] = df_merged.groupby("PERMNO").cumcount() + 1

print(df_merged[["PERMNO", "MthCalDt", "history_len"]].head(10))

    PERMNO   MthCalDt  history_len
4    10001 1995-05-31            1
5    10001 1995-06-30            2
6    10001 1995-07-31            3
7    10001 1995-08-31            4
8    10001 1995-09-29            5
9    10001 1995-10-31            6
10   10001 1995-11-30            7
11   10001 1995-12-29            8
12   10001 1996-01-31            9
13   10001 1996-02-29           10

In [23]:
# filter out those with less history

df_merged = df_merged[df_merged["history_len"] >= 36]

print(df_merged.shape)

(1501178, 23)

In [24]:
# add size feature
import numpy as np

df_merged["log_size"] = np.log(df_merged["MthCap"])

In [25]:
df_merged[
    [
        "y_next",
        "Mkt-RF",
        "SMB",
        "HML",
        "RMW",
        "CMA",
        "ret_lag1",
        "ret_lag2",
        "ret_lag3",
        "log_size",
    ]
].describe()

,y_next,Mkt-RF,SMB,HML,RMW,CMA,ret_lag1,ret_lag2,ret_lag3,log_size
count,1.501178e+06,1.501178e+06,1.501178e+06,1.501178e+06,1.501178e+06,1.501178e+06,1.501178e+06,1.501178e+06,1.501178e+06,1.501178e+06
mean,9.816671e-03,7.186500e-03,8.055255e-04,7.456492e-04,2.873589e-03,1.449806e-03,9.908208e-03,1.001075e-02,9.849561e-03,1.345007e+01
std,1.033750e-01,4.519332e-02,3.150042e-02,3.434118e-02,2.816817e-02,2.286226e-02,1.035969e-01,1.035813e-01,1.034761e-01,2.029228e+00
min,-3.021129e-01,-1.720000e-01,-1.554000e-01,-1.383000e-01,-1.895000e-01,-7.080000e-02,-3.021129e-01,-3.021129e-01,-3.021129e-01,3.936716e+00
25%,-4.032475e-02,-2.010000e-02,-1.860000e-02,-1.870000e-02,-1.190000e-02,-1.210000e-02,-4.069000e-02,-4.065575e-02,-4.086300e-02,1.204403e+01
50%,5.742000e-03,1.340000e-02,-3.000000e-04,-1.800000e-03,3.200000e-03,-6.000000e-04,5.869000e-03,6.017500e-03,5.963000e-03,1.335115e+01
75%,5.285275e-02,3.420000e-02,1.920000e-02,1.730000e-02,1.550000e-02,1.360000e-02,5.335200e-02,5.365000e-02,5.365800e-02,1.478655e+01
max,4.421290e-01,1.358000e-01,1.846000e-01,1.286000e-01,1.305000e-01,9.010000e-02,4.421290e-01,4.421290e-01,4.421290e-01,2.231688e+01

In [26]:
# Save Data Clean 2nd

df_merged.to_csv("data_clean_2.csv", index=False)